before_install:
  - ./library/download_test_roms

addons:
  apt:
    packages:
      - libudev-dev
      - libasound2-dev

language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows
