#!/bin/bash

sudo apt-get update
sudo apt-get install --yes \
    clang \
    gcc-arm-none-eabi \
    libasound2-dev \
    libclang-dev \
    libsdl2-dev \
    libudev-dev \
    llvm-dev \
    npm \
    wget

library/download_test_roms

if ! which wasm-bindgen; then
    if which cargo-binstall; then
        cargo binstall wasm-bindgen-cli
    else
        cargo install wasm-bindgen-cli
    fi
fi

if ! which wasm-opt; then
    if which cargo-binstall; then
        cargo binstall wasm-opt
    else
        cargo install wasm-opt
    fi
fi
