#!/bin/bash

sudo apt-get install --yes \
    clang \
    gcc-arm-none-eabi \
    libasound2-dev \
    libclang-dev \
    libsdl2-dev \
    libudev-dev \
    llvm-dev \
    npm \
    wget

library/download_test_roms

if ! which wasm-pack; then
    curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
fi
