#!/bin/bash

set -ex

# Run pylint on all the python
./pylint

# Run all *_test.py
for testfile in $(find . -name "*_test.py"); do
    $testfile;
done

# Generate any generated code
./code_gen

cargo build
cargo test
