#!/bin/bash

set -ex

# Run all *_test.py
for testfile in $(find . -name "*_test.py"); do
    $testfile;
done

# Run all *_gen.py
for genfile in $(find . -name "*_gen.py"); do
    $genfile;
done

cargo build
cargo test
