#!/bin/bash

set -ex

# Download the test roms
$( dirname $0 )/library/download_test_roms

if [ -z $SKIP_GIT_CHECK ]; then
    CHANGES=$( git diff )
    if [ "$CHANGES" != "" ]; then
        echo "Untracked Changes"
        exit 1;
    fi
fi

cargo build --all-features
cargo build

pushd library
cargo build --no-default-features
popd

cargo test --release

cargo bench

mkdir -p target/web_build
./web/build.py target/web_build

./pico/build.sh

cargo clippy --all-targets -- --deny "warnings"
